name: Push Docker image

on:
    push:
        branches: ["orig-qrcode-re","orig-qrcode-re-dom","bear-qrcode-ycc"]
    workflow_dispatch:

jobs:
    ToGhcr:
        name: Push to ghcr.io
        runs-on: ubuntu-latest
        env:
            image: ghcr.io/${{github.actor}}/blivechat-${{github.ref_name}}:latest
            common-image: ghcr.io/${{github.actor}}/blivechat-common-${{github.ref_name}}:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup docker buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to ghcr.io
              uses:  docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build&Push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: Dockerfile-action
                push: true
                tags: ${{env.image}}
                cache-from: type=registry,ref=${{env.image}}
                cache-to: type=inline 
            - name: Build&Push common image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: Dockerfile-common
                push: true
                tags: ${{env.common-image}}
                cache-from: type=registry,ref=${{env.common-image}}
                cache-to: type=inline 

            
            
